<?php

namespace Database\Seeders;

use App\Models\Enums\EnumCategories;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->list() as $item) {
            if (!EnumCategories::query()
                ->where('id', $item['id'])
                ->exists()) {
                $model = new EnumCategories();
                $model->fill($item);
                $model->save();
            }
        }
    }

    public function list()
    {
        return [
            [
                'id' => 1,
                'name_oz' => 'Siz uchun kitoblar',
                'name_uz' => 'Сиз учун китоблар',
                'name_ru' => 'Сиз учун китоблар',
                "parent_id" => null,
            ],
            [
                'id' => 2,
                'name_oz' => 'Badiiy kitoblar',
                'name_uz' => 'Бадиий китоблар',
                'name_ru' => 'Бадиий китоблар',
                "parent_id" => null,
            ],
            [
                'id' => 3,
                'name_oz' => 'Ilmiy ommabop kitoblar',
                'name_uz' => 'Илмий оммабоп китоблар',
                'name_ru' => 'Илмий оммабоп китоблар',
                "parent_id" => null,
            ],
            [
                'id' => 4,
                'name_oz' => 'Ilmiy tadqiqot ishlari',
                'name_uz' => 'Илмий тадқиқот ишлари',
                'name_ru' => 'Илмий тадқиқот ишлари',
                "parent_id" => null,
            ],
            [
                'id' => 5,
                'name_oz' => 'Audio kitoblar',
                'name_uz' => 'Аудио китоблар',
                'name_ru' => 'Аудио китоблар',
                "parent_id" => null,
            ],
            [
                'id' => 6,
                'name_oz' => 'Bolalar uchun',
                'name_uz' => 'Болалар учун',
                'name_ru' => 'Болалар учун',
                "parent_id" => 1,
            ],
            [
                'id' => 7,
                'name_oz' => 'Ota-onalar uchun',
                'name_uz' => 'Ота-оналар учун',
                'name_ru' => 'Ота-оналар учун',
                "parent_id" => 1,
            ],
            [
                'id' => 8,
                'name_oz' => 'Kasbga doir',
                'name_uz' => 'Касбга доир',
                'name_ru' => 'Касбга доир',
                "parent_id" => 1,
            ],
            [
                'id' => 9,
                'name_oz' => 'Shaxsiy rivojlanish',
                'name_uz' => 'Шахсий ривожланиш',
                'name_ru' => 'Шахсий ривожланиш',
                "parent_id" => 1,
            ],
            [
                'id' => 10,
                'name_oz' => 'Ruhiy tarbiya',
                'name_uz' => 'Руҳий тарбия',
                'name_ru' => 'Руҳий тарбия',
                "parent_id" => 1,
            ],
            [
                'id' => 11,
                'name_oz' => 'Rasmiy adabiyotlar',
                'name_uz' => 'Расмий адабиётлар',
                'name_ru' => 'Расмий адабиётлар',
                "parent_id" => 1,
            ],
            [
                'id' => 12,
                'name_oz' => 'Qonunlar',
                'name_uz' => 'Қонунлар',
                'name_ru' => 'Қонунлар',
                "parent_id" => 1,
            ],
            [
                'id' => 13,
                'name_oz' => "Maktab darsliklari",
                'name_uz' => 'Мактаб дарсликлари',
                'name_ru' => 'Мактаб дарсликлари',
                "parent_id" => 1,
            ],
            [
                'id' => 14,
                'name_oz' => "She'riy adabiyotlar",
                'name_uz' => 'Шеърий адабиётлар',
                'name_ru' => 'Шеърий адабиётлар',
                "parent_id" => 2,
            ],
            [
                'id' => 15,
                'name_oz' => "Ertaklar",
                'name_uz' => 'Эртаклар',
                'name_ru' => 'Эртаклар',
                "parent_id" => 2,
            ],
            [
                'id' => 16,
                'name_oz' => "Hikoyalar",
                'name_uz' => 'Ҳикоялар',
                'name_ru' => 'Ҳикоялар',
                "parent_id" => 2,
            ],
            [
                'id' => 17,
                'name_oz' => "Xalq og'zaki ijodi",
                'name_uz' => 'Халқ оғзаки ижоди',
                'name_ru' => 'Халқ оғзаки ижоди',
                "parent_id" => 2,
            ],
            [
                'id' => 18,
                'name_oz' => "Qissalar",
                'name_uz' => 'Қиссалар',
                'name_ru' => 'Қиссалар',
                "parent_id" => 2,
            ],
            [
                'id' => 19,
                'name_oz' => "Romanlar",
                'name_uz' => 'Романлар',
                'name_ru' => 'Романлар',
                "parent_id" => 2,
            ],
            [
                'id' => 20,
                'name_oz' => "O'zbek adabiyoti",
                'name_uz' => 'Ўзбек адабиёти',
                'name_ru' => 'Ўзбек адабиёти',
                "parent_id" => 2,
            ],
            [
                'id' => 21,
                'name_oz' => "Jahon adabiyoti",
                'name_uz' => 'Жаҳон адабиёти',
                'name_ru' => 'Жаҳон адабиёти',
                "parent_id" => 2,
            ],
            [
                'id' => 22,
                'name_oz' => "Psixoligiya",
                'name_uz' => 'Психолигия',
                'name_ru' => 'Психолигия',
                "parent_id" => 3,
            ],
            [
                'id' => 23,
                'name_oz' => "Siyosat",
                'name_uz' => 'Сиёсат',
                'name_ru' => 'Сиёсат',
                "parent_id" => 3,
            ],
            [
                'id' => 24,
                'name_oz' => "Ma'naviyat",
                'name_uz' => 'Маънавият',
                'name_ru' => 'Маънавият',
                "parent_id" => 3,
            ],
            [
                'id' => 25,
                'name_oz' => "Dinshunoslik",
                'name_uz' => 'Диншунослик',
                'name_ru' => 'Диншунослик',
                "parent_id" => 3,
            ],
            [
                'id' => 26,
                'name_oz' => "Adabiyotshunoslik",
                'name_uz' => 'Адабиётшунослик',
                'name_ru' => 'Адабиётшунослик',
                "parent_id" => 3,
            ],
            [
                'id' => 27,
                'name_oz' => "Jurnalistika",
                'name_uz' => 'Журналистика',
                'name_ru' => 'Журналистика',
                "parent_id" => 3,
            ],
            [
                'id' => 28,
                'name_oz' => "Davriy nashrlar(Gazeta va jurnallar)",
                'name_uz' => 'Даврий нашрлар(Газета ва журналлар)',
                'name_ru' => 'Даврий нашрлар(Газета ва журналлар)',
                "parent_id" => 3,
            ],
            [
                'id' => 29,
                'name_oz' => "Ilmiy-fantastika",
                'name_uz' => 'Илмий-фантастика',
                'name_ru' => 'Илмий-фантастика',
                "parent_id" => 3,
            ],
            [
                'id' => 30,
                'name_oz' => "Ajdodlar me'rosi",
                'name_uz' => 'Аждодлар меъроси',
                'name_ru' => 'Аждодлар меъроси',
                "parent_id" => 3,
            ],
            [
                'id' => 31,
                'name_oz' => "Prezident asarlari",
                'name_uz' => 'Президент асарлари',
                'name_ru' => 'Президент асарлари',
                "parent_id" => 3,
            ],
            [
                'id' => 32,
                'name_oz' => "Jahon durdonasi",
                'name_uz' => 'Жаҳон дурдонаси',
                'name_ru' => 'Жаҳон дурдонаси',
                "parent_id" => 3,
            ],
            [
                'id' => 33,
                'name_oz' => "Darsliklar",
                'name_uz' => 'Дарсликлар',
                'name_ru' => 'Дарсликлар',
                "parent_id" => 3,
            ],
            [
                'id' => 34,
                'name_oz' => "O'quv qo'llanmalari",
                'name_uz' => 'Ўқув қўлланмалари',
                'name_ru' => 'Ўқув қўлланмалари',
                "parent_id" => 3,
            ],
            [
                'id' => 35,
                'name_oz' => "Dars ishlanmalari",
                'name_uz' => 'Дарс ишланмалари',
                'name_ru' => 'Дарс ишланмалари',
                "parent_id" => 3,
            ],
            [
                'id' => 36,
                'name_oz' => "Turli sohalar",
                'name_uz' => 'Турли соҳалар',
                'name_ru' => 'Турли соҳалар',
                "parent_id" => 3,
            ],
            [
                'id' => 37,
                'name_oz' => "Referatlar",
                'name_uz' => 'Рефератлар',
                'name_ru' => 'Рефератлар',
                "parent_id" => 4,
            ],
            [
                'id' => 38,
                'name_oz' => "Kurs ishlari",
                'name_uz' => 'Курс ишлари',
                'name_ru' => 'Курс ишлари',
                "parent_id" => 4,
            ],
            [
                'id' => 39,
                'name_oz' => "Bitiruv malakaviy ishlari",
                'name_uz' => 'Битирув малакавий ишлари',
                'name_ru' => 'Битирув малакавий ишлари',
                "parent_id" => 4,
            ],
            [
                'id' => 40,
                'name_oz' => "Magistrlik disertatsiyalari",
                'name_uz' => 'Магистрлик дисертациялари',
                'name_ru' => 'Магистрлик дисертациялари',
                "parent_id" => 4,
            ],
            [
                'id' => 41,
                'name_oz' => "Ilmiy maqolalar",
                'name_uz' => 'Илмий мақолалар',
                'name_ru' => 'Илмий мақолалар',
                "parent_id" => 4,
            ],
            [
                'id' => 42,
                'name_oz' => "Tezislar",
                'name_uz' => 'Тезислар',
                'name_ru' => 'Тезислар',
                "parent_id" => 4,
            ],
            [
                'id' => 43,
                'name_oz' => "Avtoreferatlar",
                'name_uz' => 'Авторефератлар',
                'name_ru' => 'Авторефератлар',
                "parent_id" => 4,
            ],
            [
                'id' => 44,
                'name_oz' => "Disertatsiyalar",
                'name_uz' => 'Дисертациялар',
                'name_ru' => 'Дисертациялар',
                "parent_id" => 4,
            ],
            [
                'id' => 45,
                'name_oz' => "Janrlar bo'yicha",
                'name_uz' => 'Жанрлар бўйича',
                'name_ru' => 'Жанрлар бўйича',
                "parent_id" => 2,
            ],
            [
                'id' => 46,
                'name_oz' => "Fantastika",
                'name_uz' => 'Фантастика',
                'name_ru' => 'Фантастика',
                "parent_id" => 45,
            ],
            [
                'id' => 47,
                'name_oz' => "Tarixiy",
                'name_uz' => 'Тарихий',
                'name_ru' => 'Тарихий',
                "parent_id" => 45,
            ],
            [
                'id' => 48,
                'name_oz' => "Sarguzasht",
                'name_uz' => 'Саргузашт',
                'name_ru' => 'Саргузашт',
                "parent_id" => 45,
            ],
            [
                'id' => 49,
                'name_oz' => "Sayohat",
                'name_uz' => 'Саёҳат',
                'name_ru' => 'Саёҳат',
                "parent_id" => 45,
            ],
            [
                'id' => 50,
                'name_oz' => "Biografik",
                'name_uz' => 'Биографик',
                'name_ru' => 'Биографик',
                "parent_id" => 45,
            ],
            [
                'id' => 51,
                'name_oz' => "O'zbek romanchiligi",
                'name_uz' => 'Ўзбек романчилиги',
                'name_ru' => 'Ўзбек романчилиги',
                "parent_id" => 45,
            ],
            [
                'id' => 52,
                'name_oz' => "Dostonlar",
                'name_uz' => 'Достонлар',
                'name_ru' => 'Достонлар',
                "parent_id" => 45,
            ],
            [
                'id' => 53,
                'name_oz' => "Hajviya",
                'name_uz' => 'Ҳажвия',
                'name_ru' => 'Ҳажвия',
                "parent_id" => 45,
            ],
            [
                'id' => 54,
                'name_oz' => "Fojeaviy",
                'name_uz' => 'Фожеавий',
                'name_ru' => 'Фожеавий',
                "parent_id" => 45,
            ],
            [
                'id' => 55,
                'name_oz' => "Antiutopiya",
                'name_uz' => 'Антиутопия',
                'name_ru' => 'Антиутопия',
                "parent_id" => 45,
            ],
            [
                'id' => 56,
                'name_oz' => "Diniy-ma'rifiy",
                'name_uz' => 'Диний-маърифий',
                'name_ru' => 'Диний-маърифий',
                "parent_id" => 45,
            ],
            [
                'id' => 57,
                'name_oz' => "Fan tarmoqlari bo'yicha",
                'name_uz' => 'Фан тармоқлари бўйича',
                'name_ru' => 'Фан тармоқлари бўйича',
                "parent_id" => 4,
            ],
            [
                'id' => 58,
                'name_oz' => "01.00.00 - Fizika-matematika fanlari (FM)",
                'name_uz' => '01.00.00 - Физика-математика фанлари (ФМ)',
                'name_ru' => '01.00.00 - Физика-математика фанлари (ФМ)',
                "parent_id" => 57,
            ],
            [
                'id' => 58,
                'name_oz' => "02.00.00 - Kimyo fanlari (K)",
                'name_uz' => '02.00.00 - Кимё фанлари (К)',
                'name_ru' => '02.00.00 - Кимё фанлари (К)',
                "parent_id" => 57,
            ],
            [
                'id' => 59,
                'name_oz' => "03.00.00 - Biologiya fanlari (B)",
                'name_uz' => '03.00.00 - Биология фанлари (Б)',
                'name_ru' => '03.00.00 - Биология фанлари (Б)',
                "parent_id" => 57,
            ],
            [
                'id' => 60,
                'name_oz' => "04.00.00 - Geologiya-mineralogiya fanlari (GM)",
                'name_uz' => '04.00.00 - Геология-минералогия фанлари (ГМ)',
                'name_ru' => '04.00.00 - Геология-минералогия фанлари (ГМ)',
                "parent_id" => 57,
            ],
            [
                'id' => 61,
                'name_oz' => "05.00.00 - Texnika fanlari (T)",
                'name_uz' => '05.00.00 - Техника фанлари (Т)',
                'name_ru' => '05.00.00 - Техника фанлари (Т)',
                "parent_id" => 57,
            ],
            [
                'id' => 62,
                'name_oz' => "06.00.00 - Qishloq xo'jaligi fanlari (Qx)",
                'name_uz' => '06.00.00 - Қишлоқ хўжалиги фанлари (Қх)',
                'name_ru' => '06.00.00 - Қишлоқ хўжалиги фанлари (Қх)',
                "parent_id" => 57,
            ],
            [
                'id' => 63,
                'name_oz' => "07.00.00 - Tarix fanlari (Tar)",
                'name_uz' => '07.00.00 - Тарих фанлари (Тар)',
                'name_ru' => '07.00.00 - Тарих фанлари (Тар)',
                "parent_id" => 57,
            ],
            [
                'id' => 64,
                'name_oz' => "08.00.00 - Iqtisodiyot fanlari (I)",
                'name_uz' => '08.00.00 - Иқтисодиёт фанлари (И)',
                'name_ru' => '08.00.00 - Иқтисодиёт фанлари (И)',
                "parent_id" => 57,
            ],
            [
                'id' => 65,
                'name_oz' => "09.00.00 - Falsafa fanlari (F)",
                'name_uz' => '09.00.00 - Фалсафа фанлари (Ф)',
                'name_ru' => '09.00.00 - Фалсафа фанлари (Ф)',
                "parent_id" => 57,
            ],
            [
                'id' => 66,
                'name_oz' => "10.00.00 - Filologiya fanlari (Fil)",
                'name_uz' => '10.00.00 - Филология фанлари (Фил)',
                'name_ru' => '10.00.00 - Филология фанлари (Фил)',
                "parent_id" => 57,
            ],
            [
                'id' => 67,
                'name_oz' => "11.00.00 - Geografiya fanlari (Gr)",
                'name_uz' => '11.00.00 - География фанлари (Гр)',
                'name_ru' => '11.00.00 - География фанлари (Гр)',
                "parent_id" => 57,
            ],
            [
                'id' => 68,
                'name_oz' => "12.00.00 - Yuridik fanlari (Yu)",
                'name_uz' => '12.00.00 - Юридик фанлари (Ю)',
                'name_ru' => '12.00.00 - Юридик фанлари (Ю)',
                "parent_id" => 57,
            ],
            [
                'id' => 69,
                'name_oz' => "13.00.00 - Pedagogika fanlari (Ped)",
                'name_uz' => '13.00.00 - Педагогика фанлари (Пед)',
                'name_ru' => '13.00.00 - Педагогика фанлари (Пед)',
                "parent_id" => 57,
            ],
            [
                'id' => 70,
                'name_oz' => "14.00.00 - Tibbiyot fanlari (Tib)",
                'name_uz' => '14.00.00 - Тиббиёт фанлари (Тиб)',
                'name_ru' => '14.00.00 - Тиббиёт фанлари (Тиб)',
                "parent_id" => 57,
            ],
            [
                'id' => 71,
                'name_oz' => "15.00.00 - Farmatseftika fanlari (Far)",
                'name_uz' => '15.00.00 - Фармацефтика фанлари (Фар)',
                'name_ru' => '15.00.00 - Фармацефтика фанлари (Фар)',
                "parent_id" => 57,
            ],
            [
                'id' => 72,
                'name_oz' => "16.00.00 - Veterinariya fanlari (V)",
                'name_uz' => '16.00.00 - Ветеринария фанлари (В)',
                'name_ru' => '16.00.00 - Ветеринария фанлари (В)',
                "parent_id" => 57,
            ],
            [
                'id' => 73,
                'name_oz' => "17.00.00 - San'atshunoslik fanlari (San)",
                'name_uz' => '17.00.00 - Санъатшунослик фанлари (Сан)',
                'name_ru' => '17.00.00 - Санъатшунослик фанлари (Сан)',
                "parent_id" => 57,
            ],
            [
                'id' => 74,
                'name_oz' => "18.00.00 - Arxitektura fanlari (A)",
                'name_uz' => '18.00.00 - Архитектура фанлари (А)',
                'name_ru' => '18.00.00 - Архитектура фанлари (А)',
                "parent_id" => 57,
            ],
            [
                'id' => 75,
                'name_oz' => "19.00.00 - Psixologiya fanlari (P)",
                'name_uz' => '19.00.00 - Психология фанлари (П)',
                'name_ru' => '19.00.00 - Психология фанлари (П)',
                "parent_id" => 57,
            ],
            [
                'id' => 76,
                'name_oz' => "20.00.00 - Sotsiologiya fanlari (S)",
                'name_uz' => '20.00.00 - Социология фанлари (С)',
                'name_ru' => '20.00.00 - Социология фанлари (С)',
                "parent_id" => 57,
            ],
            [
                'id' => 77,
                'name_oz' => "21.00.00 - Siyosiy fanlar (Ss)",
                'name_uz' => '21.00.00 - Сиёсий фанлар (Сс)',
                'name_ru' => '21.00.00 - Сиёсий фанлар (Сс)',
                "parent_id" => 57,
            ],
            [
                'id' => 78,
                'name_oz' => "22.00.00 - Islomshunoslik fanlari (Isl)",
                'name_uz' => '22.00.00 - Исломшунослик фанлари (Исл)',
                'name_ru' => '22.00.00 - Исломшунослик фанлари (Исл)',
                "parent_id" => 57,
            ],
        ];
    }
}
